### ISSUE TITLE
Posting -> Services 

### ISSUE THREAD

**Issue by bulatbulat48** [ArthurG/Kijiji-Repost-Headless#101]
postAdForm.adType: OFFER
postAdForm.priceType: CONTACT
postAdForm.city: Markham
postAdForm.province: 'ON'
postAdForm.postalCode: L3T 7T7
postAdForm.addressCity: Markham
postAdForm.addressProvince: 'ON'
postAdForm.addressPostalCode: L3T 7T7
postAdForm.geocodeLat: '43.84009289999999'
postAdForm.geocodeLng: '-79.39002160000001'
postAdForm.locationId: 1700273
PostalLat: '43.84009289999999'
PostalLng: '-79.39002160000001'
locationLevel0: 1700272
topAdDuration: '7'
submitType: saveAndCheckout
postAdForm.title: title
postAdForm.description: description
categoryId: '166'
image_paths: [2223.jpg]

--------------------------
Image upload success on try #1
Failed ad post attempt #2, giving up.

**Comment by jackm** [comment]
This issue can be merged into #100 ; they're effectively the same issue.
