### ISSUE TITLE
Cant figure out the posting/reposting command

### ISSUE THREAD

**Issue by Evanskr** [ArthurG/Kijiji-Repost-Headless#110]
Whenever I try to post, I get this:

```
evans-mbp:~ evans$ python3 kijiji_repost_headless [-u USERNAME] [-p PASSWORD] post myproduct/item.yml
usage: kijiji_repost_headless [-h] [-u USERNAME] [-p PASSWORD]
                              {post,show,delete,nuke,check_ad,repost,build_ad}
                              ...
kijiji_repost_headless: error: invalid choice: '[-u' (choose from 'post', 'show', 'delete', 'nuke', 'check_ad', 'repost', 'build_ad')
```

Please help...

**Comment by jackm** [comment]
Square brackets indicate an optional argument, where as arguments without any decoration are required. You don't include the brackets when you actually run the command. This follows the standard interface for command line programs.

Here's a more [in-depth description](http://docopt.org/) of using command line programs with arguments.

**Comment by Evanskr** [comment]
Thankyou, I feel dumb now...
