### ISSUE TITLE
Exception when posting

### ISSUE THREAD

**Issue by rockerrullz** [ArthurG/Kijiji-Repost-Headless#111]
I ran today a few times the scripts and everytime I get this error: 

> KijijiApiException("'initialXsrfToken' not found in html text.", resp.text)

Did they change again the way they provice the XSRF Token?

**Comment by jackm** [comment]
Could you provide more information regarding the ad category you are trying to post to? Could you also include the html file that is created after the exception occurs?

I am not able to reproduce this myself. I'm still able to repost ads ad per usual without any issues, but they are all in the more common categories (eg. electronics, books, etc.)

**Comment by Aluui** [comment]
Quick update on this issue: I am also running into this when I run the app on a headless linux server.
However, when I run the app on my windows desktop, it works as expected.

Does the application rely on gui settings from the local pc to work?

**Comment by Aluui** [comment]
Yes it is. I tried hosting the application on https://www.pythonanywhere.com so I could run it online without using my pc. I can share the terminal session with you if you want to take a look.

**Comment by Aluui** [comment]
![image](https://user-images.githubusercontent.com/34776107/51651018-039d5c80-1f50-11e9-8ae6-c0f852ef66da.png)

**Comment by jackm** [comment]
I've never heard of or used that cloud service before, but it's possible it could be behaving differently than if you just ran it locally. I would recommend installing python locally and running it that way.

**Comment by Aluui** [comment]
It works locally. I also tried creating an AWS EC2 instance of a linux server. I installed python3.4 and all the requirements. I get the exact same error there.

I think running it locally or on a machine with a gui is required for it to work.

**Comment by jackm** [comment]
Can you also check for a kijijiapi_dump*.html file in the repo root directory? It should contain a dump of the Kijiji html page that it got. You can look through that to see if the web page makes sense; it may also show errors that the Kijiji site returned.

**Comment by ArthurG** [comment]
I had problems with EC2 instances as well when I was using this extension. I believe Kijiji bans all Amazon IP addresses. If you really want to run this on a linux server, your server will need to be self hosted from your own residential IP address.
