### ISSUE TITLE
Posting Command

### ISSUE THREAD

**Issue by GeneralDictator** [ArthurG/Kijiji-Repost-Headless#113]
Hi, I am new here,
and I am having trouble posting the ad. I was able to generate the yml file, but now if I run the command python kijiji_repost_headless post item.yml on the python shell, it tell me kijiji_repost_headless invalid syntax.

I am guaranteed that I am doing this wrong, so if anyone can guide me the right way.

Thank You

**Comment by dealerboost** [comment]
The commande line is:

python kijiji_repost_headless -u **your-username** -p **your-password** post item.yml

**Comment by jackm** [comment]
Don't run this in a _python shell_, run it in a regular (eg. bash) shell.

**Comment by GeneralDictator** [comment]
![kijiji](https://user-images.githubusercontent.com/43127575/45334567-4b938800-b549-11e8-950a-a77922b3655d.PNG)

but my file exists... i even tried going to the directory and using the command but does not work. 

Thank You in advance.

**Comment by jackm** [comment]
The shell is saying that the folder `kijiji_repost_headless` doesn't exist. Are you _certain_ that folder is within the current directory `C:\Users`?

**Comment by jackm** [comment]
@ArthurG you can probably close this one. He hasn't responded back in about a month now. I believe it is just user error.
