### ISSUE TITLE
Invalid Map API token?

### ISSUE THREAD

**Issue by dealerboost** [ArthurG/Kijiji-Repost-Headless#114]
Hey guys, since this morning I am not able to post an ad . See pictures 
![capture](https://user-images.githubusercontent.com/36820040/45301375-d5f2d200-b4de-11e8-81fc-2fb8fc360a2c.JPG)

**Comment by jackm** [comment]
I don't think this has anything to do with a map API. Looks like your ad file has invalid yaml syntax in it. Most like you are using a special yaml character where it isn't expected without quoting it which is confusing the parser.
How did you create your ad file? Did you generate it using "build ad" or did you write it manually?

**Comment by dealerboost** [comment]
Got it. You were right, special characters like ' is not allowed. Ad desc was in french ;)

Thank you

**Comment by jackm** [comment]
Did you generate the ad file using "build ad" subcommand or did you edit it manually? If you only used the "build ad" method and it gave invalid yaml syntax then there is a bug that needs to be addressed.

**Comment by dealerboost** [comment]
Yes I did use the build ad command and then edited it manually. Fixed already, everything works fine now

**Comment by jackm** [comment]
@ArthurG please close this
