### ISSUE TITLE
Keyless access to Google Maps Platform is deprecated. 

### ISSUE THREAD

**Issue by zcharleshebert** [ArthurG/Kijiji-Repost-Headless#116]
Hello there, it seems `build_ad` command no works anymore. 
I get the following error message from google maps platform: 

> Maps API error: Keyless access to Google Maps Platform is deprecated. Please use an API key with all your API calls to avoid service interruption. For further details please refer to http://g.co/dev/maps-no-account

**Comment by zcharleshebert** [comment]
Worked with a specific format, nvm.

**Comment by NipBoss** [comment]
Can you please explain how to fix?
