### ISSUE TITLE
Address entry issue

### ISSUE THREAD

**Issue by NipBoss** [ArthurG/Kijiji-Repost-Headless#117]
Whatever address I enter I get an error saying "Maps API error: Keyless access to Google Maps Platform is deprecated. Please use an API key with all your API calls to avoid service interruption. For further details please refer to http://g.co/dev/maps-no-account"

**Comment by zachatkinson** [comment]
Having the same issue. I noticed a user mentioned the fix had to do with the address format you supply as 'your address' but I have not been able to figure out what that format is, yet!

**Comment by zachatkinson** [comment]
Figured it out. I entered an address for the CN Tower in Toronto in Google maps.  I then took a look at the URL that was generated.  The address in question is:

301 Front Street W, Toronto ON M5V 2T6

and the URL writes it as:

+301+Front+St+W,+Toronto,+ON+M5V+2T6

Once I used the plus signs and cut and paste the address from the URL I was able to bypass this error. Hope this helps you NipBoss.

**Comment by NipBoss** [comment]
Thanks @zachatkinson
