### ISSUE TITLE
Issue with login

### ISSUE THREAD

**Issue by dealerboost** [ArthurG/Kijiji-Repost-Headless#118]
I don't know if Kijiji's API changed but I cant login anymore. When I check dump file, my password is in username field...
![revrvrvr](https://user-images.githubusercontent.com/36820040/46249840-d4416d80-c3fd-11e8-9e71-3813844f780e.JPG)

**Comment by vipertemp** [comment]
As of 8 minutes ago, I am not having any problems logging in with the API.
