### ISSUE TITLE
Exception on Post

### ISSUE THREAD

**Issue by torqueNoFriction** [ArthurG/Kijiji-Repost-Headless#124]
When I try to post an add I get the following exception, any idea why ?
`
Image upload success on try #1                                                                                          Traceback (most recent call last):                                                                                        File "C:\Program Files\Python37\lib\runpy.py", line 193, in _run_module_as_main                                           "__main__", mod_spec)                                                                                                 File "C:\Program Files\Python37\lib\runpy.py", line 85, in _run_code                                                      exec(code, run_globals)                                                                                               File "kijiji_repost_headless\__main__.py", line 195, in <module>                                                          main()                                                                                                                File "kijiji_repost_headless\__main__.py", line 51, in main                                                               args.function(args)                                                                                                   File "kijiji_repost_headless\__main__.py", line 95, in post_ad                                                            api.post_ad_using_data(data, image_files)                                                                             File "kijiji_repost_headless\kijiji_api.py", line 202, in post_ad_using_data                                              raise KijijiApiException("Could not post ad.", resp.text)                                                           kijiji_api.KijijiApiException: Could not post ad
`

**Comment by jackm** [comment]
Could you please open the `kijijiapi_dump_*.html` file that was generated in your browser and see if there are any error messages shown on the page? It's possible that Kijiji was expecting an additional form field but didn't receive it and thus refused to post the ad.

**Comment by torqueNoFriction** [comment]
Where would this be ? I am unable to find such a file.

**Comment by jackm** [comment]
The dump file should be created within the current directory of where you executed the `kijiji_repost_headless` module.

**Comment by torqueNoFriction** [comment]
@jackm any category is doing this (I have 10 adds), some it camping+outdoor some in phones etc.

**Comment by torqueNoFriction** [comment]
You can close this post. I beleive previously I got banned from kijiji due to posting too many times back to back. Tried it with a new account and all worked.
