### ISSUE TITLE
requests.exceptions.HTTPError: 500 Server Error:  for url: https://www.kijiji.ca/p-submit-ad.html

### ISSUE THREAD

**Issue by QwertyCoolMT** [ArthurG/Kijiji-Repost-Headless#126]
c:\xxxxxxxx>python KijijiBot post ad-01.yml
Image upload success on try #1
Image upload success on try #1
Image upload success on try #1
Image upload success on try #1
Image upload success on try #1
Traceback (most recent call last):
  File "C:\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "KijijiBot\__main__.py", line 195, in <module>
    main()
  File "KijijiBot\__main__.py", line 51, in main
    args.function(args)
  File "KijijiBot\__main__.py", line 95, in post_ad
    api.post_ad_using_data(data, image_files)
  File "KijijiBot\kijiji_api.py", line 196, in post_ad_using_data
    resp.raise_for_status()
  File "C:\Python36\lib\site-packages\requests\models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url: https://www.kijiji.ca/p-submit-ad.html

started happening recently only on ads in Real estate rental appartments...

**Comment by QwertyCoolMT** [comment]
It's because its another one of the categories they've added their "feature Package" stuff to. Fixed on my end, but this is going to be an ever changing thing that will constantly break categories..

**Comment by Jester8813** [comment]
Hey Qwerty can you provide some details on how you fixed the Feature Package? I think that is what is wrong with my script posting in the cabinets and counter tops under home renovations section.

**Comment by NataliaTheodora** [comment]
C:\Users\Ava.Haywar\Python\Kijiji-Repost-Headless-master>python kijiji_repost_headless -u xxxx@gmail.com -p xxxx post ad\item.yml
Image upload success on try #1
Image upload success on try #1
Image upload success on try #1
Image upload success on try #1
Image upload success on try #1
Image upload success on try #1
Image upload success on try #1
Image upload success on try #1
Traceback (most recent call last):
  File "C:\Users\Ava.Hayward\Python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Ava.Hayward\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "kijiji_repost_headless\__main__.py", line 195, in <module>
    main()
  File "kijiji_repost_headless\__main__.py", line 51, in main
    args.function(args)
  File "kijiji_repost_headless\__main__.py", line 95, in post_ad
    api.post_ad_using_data(data, image_files)
  File "kijiji_repost_headless\kijiji_api.py", line 197, in post_ad_using_data
    resp.raise_for_status()
  File "C:\Users\Ava.Hayward\Python\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url: https://www.kijiji.ca/p-submit-ad.html

**Comment by Smurfie8981** [comment]
Hi guys, 

I ran into a similar issue when running the script. is there any quick fix I can implement to get around this?

C:\Users\James.Smith\Desktop\Archive\ArchivePersonal\Python\Kijiji-Repost-Headless-master>python kijiji_repost_headless -u xxxxx@gmail.com -p xxxxx post ad\item.yml
Image upload success on try #1
Image upload success on try #1
Image upload success on try #1
Image upload success on try #1
Image upload success on try #1
Image upload success on try #1
Image upload success on try #1
Image upload success on try #1
Traceback (most recent call last):
  File "C:\Users\James.Smith\Python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\James.Smith\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "kijiji_repost_headless\__main__.py", line 195, in <module>
    main()
  File "kijiji_repost_headless\__main__.py", line 51, in main
    args.function(args)
  File "kijiji_repost_headless\__main__.py", line 95, in post_ad
    api.post_ad_using_data(data, image_files)
  File "kijiji_repost_headless\kijiji_api.py", line 197, in post_ad_using_data
    resp.raise_for_status()
  File "C:\Users\James.Smith\Python\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url: https://www.kijiji.ca/p-submit-ad.html

Thanks, 
J.S

**Comment by CabbageSmell** [comment]
> happening only on ads in Real estate rental apartments...
I just discovered Kijiji-Repost-Headless and I am trying to post an apartment.  It works but only if I post it as a House in Real Estate Rentals, lol!  But as the OP said, the apartments category is broken.

 QwertyCoolMT commented 
> It's because its another one of the categories they've added their "feature Package" stuff to. Fixed on my end, but this is going to be an ever changing thing that will constantly break categories..

Please post your fix!  This is waaay beyond my brain.  The "feature Package" leads to a url instead of posting the ad.  
`requests.exceptions.HTTPError: 500 Server Error: for url: https://www.kijiji.ca/p-submit-ad.html`

**Comment by ArthurG** [comment]
> It's because its another one of the categories they've added their "feature Package" stuff to. Fixed on my end, but this is going to be an ever changing thing that will constantly break categories..

Please submit a PR for these changes, @QwertyCoolMT. It's extremely difficult for me to discover and fix these problems since I don't run ads in a lot of categories everyone else is using. 

Thanks!

**Comment by dwiggles** [comment]
Brand new to this, and yes, using it to post about real_estate and, yes, the same error message.

Not knowing where to start the repair process, my first attempt is to use this, 
    kijiji_repost_headless/save_attribute_map_to_json.py
to rebuild this file,
    kijiji_repost_headless/kijiji_categories_attrs.json

Why? 

Not sure! :) ...but this approach seems to be hinted at in the comment from QwertyCoolMT, 
> It's because its another one of the categories they've added their "feature Package" stuff to. 
> Fixed on my end, but this is going to be an ever changing thing that will constantly break
> categories.

That is, I presume that QwertyCoolMT simply rebuilt the categories file... that simple!  (please, somebody comment on this point... such as, "Exactly!" or else "don't waste your time!")

In any event, this does not work for me.  In a surprising way...

That is, I executed "save_attri..." and it chugged away promisingly for a minute or two, verbosely dumping reassuring messages like this, 

> ...
> Searching category_id 30353001
> Searching category_id 737
> Searching category_id 30349001
> Searching category_id 14922003
> ...

However, when it finally concluded, I could see that the new categores json looked wrong:

> -rw-r--r--   1 dw  staff     2 24 Jun 07:57 kijiji_categories_attrs.json

Yeah. 2 bytes. Just these two:

> []

I had inspected this json prior to that and it was indeed what you would expect... and a lot longer than 2 bytes. 

bites. 

And no error messages/warnings. 

So, now I'm faced with figuring out why this failed. However, I don't even know if I'm on the right track. 

Whatever. Just thought I would share. Sometimes articulating the issue helps me sort it out.... Not helping... maybe it will help later. ;)

**Comment by ArthurG** [comment]
I believe #150 should fix this issue. Please LMK if this issue is still present.
