### ISSUE TITLE
kijiji_api.KijijiApiException: Could not log in.

### ISSUE THREAD

**Issue by jamieeyre** [ArthurG/Kijiji-Repost-Headless#129]
I try to call the show funtion, and I am no longer able to login. I checked the credentials, and they are correct. Anyone else have this issue?

python3 kijiji_repost_headless -u mymail@mail.com -p 'xxxxxx' show

  File "kijiji_repost_headless/kijiji_api.py", line 101, in login
    raise KijijiApiException("Could not log in.", resp.text)
kijiji_api.KijijiApiException: Could not log in.

**Comment by iqtedar123** [comment]
I'm having the same issue when I repost an ad.

**Comment by jamieeyre** [comment]
@iqtedar123 It was working for me yesterday. Problem just started this morning.

**Comment by jamieeyre** [comment]
@iqtedar123 A quick fix is to comment out lines 100 and 101 in kijiji_api.py

It seems the t-login.html no longer returns 200 with an html as a response but rather a 302 and no response.

        #if not self.is_logged_in():
        #    raise KijijiApiException("Could not log in.", resp.text)

**Comment by vipertemp** [comment]
Likewise for me since *yesterday* 9 AM-ish (not today). The inconsistency is perplexing. What's the fix?

**Comment by iqtedar123** [comment]
@jamieeyre Thanks. That fix worked for me.

**Comment by zachatkinson** [comment]
@jamieeyre lifesaver, this worked for me too.  hopefully this is another change that can be added by @ArthurG

**Comment by jackytai** [comment]
@jamieeyre Thank you so much!

**Comment by Arephan** [comment]
Thank you so much! @ArthurG please add the fix!

**Comment by ArthurG** [comment]
If you discover fixes, please submit a PR and I will approve it. This will make it much faster to merge changes

@jamieeyre

**Comment by michaelkuzmin** [comment]
@ArthurG just wondering, was this issue supposed to be closed? I just experienced the same issue, re-downloaded the entire thing, the issue did not go away, searched open issues, then searched closed issues and found this :) maybe we should reopen the issue or fix the current code?

**Comment by ArthurG** [comment]
Tried fixing this issue again. LMK if you still f.
