### ISSUE TITLE
Enhancement : Create a package for pypi

### ISSUE THREAD

**Issue by Hatoris** [ArthurG/Kijiji-Repost-Headless#134]
Hello,

I was just wondering if is there a reason to not create a package that will be easily installed with a simple `pip install Kijiji-Repost-Headless` ?

**Comment by vipertemp** [comment]
I wonder what's going to happen when everyone on the planet gets their hands on this.

**Comment by Hatoris** [comment]
It will never happen because this package have more than two years, and since it's creation it still works and not everyone use it. People who used this app are people that will not pay for features on Kijiji, moreover Kijiji have some limitation on number of post and does not allow duplicate. 

What is you opinion? Do you think that put it on pypi will bring more people? Clone this package is not difficult too.

**Comment by vipertemp** [comment]
More exposure than necessary brings it one step closer to being shut down, or even further limited. Things were better ever 2 years ago and I did notice they started putting increasingly tighter limitations on around then. That's my opinion.

**Comment by jackm** [comment]
I'm also on the side of not putting this on pypi. I too worry that too much exposure would mean that Kijiji would be more active in modifying their backend to deter the use of tools like this.

**Comment by Aluui** [comment]
*phew* another doomsday topic avoided 😛

**Comment by Hatoris** [comment]
That the power of community and discussions.:)
