### ISSUE TITLE
Extract yml from an ad already uploaded

### ISSUE THREAD

**Issue by martindmtrv** [ArthurG/Kijiji-Repost-Headless#135]
Pulling all the relevant data required for the .yml from an ad already uploaded would be amazing! You'd have to manually specify the directories for the images and maybe anything else that cannot be found from the ad itself, but it would be a huge time saver for someone to start using this amazing api! Plus then you could use Kijiji's normal Post Ad functionality, then repost with this program!

**Comment by jackm** [comment]
Same request as #64 

It would be a nice feature for sure, but it also would require ongoing maintenance if you choose to scrape HTML from the ad page; anytime Kijiji changes their ad HTML, the scraper would also need to be updated to match.

If someone could discover an API or json HTTP request to get all of this ad info though, that would be much better.

**Comment by vipertemp** [comment]
Out of curiosity, how was the API and its commands discovered in the first place?
