### ISSUE TITLE
Add "Nintendo Switch" as section in Video Games

### ISSUE THREAD

**Issue by Pileot** [ArthurG/Kijiji-Repost-Headless#148]
Kijiji recently added a "Nintendo Switch" section for ads in video games yet it is not an option when creating an ad. Can you please have a look into adding it so we don't have to post in "Video Games Other", thanks.

**Comment by ArthurG** [comment]
Could you please take a look at how save_attribute_map_to_json.py works and generate it yourself? Afterward, please submit a PR with your fix.

Thanks!

**Comment by Pileot** [comment]
Im sorry, Im super terrible at programming... I did somehow manage to muddle something together, I added the following line to kijiji_categories_attrs.json basically copy pasting the section from a similar category and changing the category ID to 33035001 (randomly found that number when browsing the source of the Kijiji site, not sure if its technically correct but for now, for me, it seems to work). I don't know how to add / change the files in the github to make the changes work for everyone but heres what I got that works well enough for me:

{"category_id": 33035001, "category_name": "Buy & Sell>Video Games & Consoles>Nintendo Switch", "attributes": [{"attribute_human_readable": "Price:", "attribute_type": "input", "attribute_name": "postAdForm.priceAmount"}, {"attribute_human_readable": "Ad Title:", "attribute_type": "input", "attribute_name": "postAdForm.title"}, {"attribute_human_readable": "PhoneNumber", "attribute_type": "input", "attribute_name": "postAdForm.phoneNumber"}, {"attribute_human_readable": "", "attribute_options": [{"option_human_readable": "I am offering - You are offering an item for sale", "option_name": "OFFER"}, {"option_human_readable": "I want - You want to buy an item", "option_name": "WANTED"}], "attribute_type": "radio", "attribute_name": "postAdForm.adType"}, {"attribute_human_readable": "", "attribute_options": [{"option_human_readable": "$", "option_name": "FIXED"}, {"option_human_readable": "Free", "option_name": "GIVE_AWAY"}, {"option_human_readable": "Please Contact", "option_name": "CONTACT"}, {"option_human_readable": "Swap / Trade", "option_name": "SWAP_TRADE"}], "attribute_type": "radio", "attribute_name": "postAdForm.priceType"}, {"attribute_human_readable": "For Sale By:", "attribute_options": [{"option_human_readable": "Owner", "option_name": "ownr"}, {"option_human_readable": "Business", "option_name": "delr"}], "attribute_type": "radio", "attribute_name": "postAdForm.attributeMap[forsaleby_s]"}]},

**Comment by ArthurG** [comment]
#151  should fix this
