### ISSUE TITLE
Issue using this project

### ISSUE THREAD

**Issue by vowswithin** [ArthurG/Kijiji-Repost-Headless#149]
I am not sure if this is a user issue (I feel like maybe it is) but I have installed python 3 + dependencies. I was able to use **python kijiji_repost_headless build_ad** to build an ad and I was able to use show command to see which ads existed already and then finally when I went to post the ad it wouldn't work, here is the output

C:\Users\Jamie\Desktop\Kijiji-Repost-Headless-master>python kijiji_repost_headless -u *removed for security* -p *removed for security* post Armoire/Armoire.yml
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "kijiji_repost_headless\__main__.py", line 204, in <module>
    main()
  File "kijiji_repost_headless\__main__.py", line 51, in main
    args.function(args)
  File "kijiji_repost_headless\__main__.py", line 83, in post_ad
    [data, image_files] = get_post_details(args.ad_file)
  File "kijiji_repost_headless\__main__.py", line 69, in get_post_details
    files = [open(os.path.join(os.path.dirname(ad_file), picture), 'rb').read() for picture in data['image_paths']]
  File "kijiji_repost_headless\__main__.py", line 69, in <listcomp>
    files = [open(os.path.join(os.path.dirname(ad_file), picture), 'rb').read() for picture in data['image_paths']]
FileNotFoundError: [Errno 2] No such file or directory: 'Armoire\\'

path wise I have the following

/desktop/Kijiji-Repost-Headless-master <--- root folder
/desktop/Kijiji-Repost-Headless-master/kijiji_repost_headless
/desktop/Kijiji-Repost-Headless-master/Armoire/    <--- contains jpgs + Armoire.yml I generated
/desktop/Kijiji-Repost-Headless-master/tests/

If anyone has a few seconds to help me I would really appreciate it, I have only used a few python scripts but was able to get them working relatively easy.

**Comment by jackm** [comment]
The path to the ad images is relative to where the yaml file is located. If your images are within the same directory as the yaml file, then do not prefix them with a path.

As it is right now, it is trying to file an image file at `/desktop/Kijiji-Repost-Headless-master/Armoire/Armoire/my_ad_image_file.jpg` and it does not find the directory `desktop/Kijiji-Repost-Headless-master/Armoire/Armoire/` because it does not exist.

**Comment by vowswithin** [comment]
I had it that way before. I realized that I needed to name the images, I thought it just asked how many and went into the folder and automatically selected them... that was a dumb mistake

Thanks so much :-D
