### ISSUE TITLE
Ads Being Deleted

### ISSUE THREAD

**Issue by xtthew** [ArthurG/Kijiji-Repost-Headless#154]
I tried posting Ads with the script, but every time it's posted I'll get the email from Kijiji saying that ad has been posted.. but when I go to look at it, it's been removed. Is there any documentation on how to avoid this happening?

**Comment by vipertemp** [comment]
To which category(ies)?

**Comment by xtthew** [comment]
To the 'Services > Other' category.

**Comment by vipertemp** [comment]
That category would be why.

**Comment by xtthew** [comment]
What's wrong with that category? It comes up as a valid option when building the yml

**Comment by vipertemp** [comment]
Nothing. I suspect they have set some kind of special condition on that category on the API side that causes this problem.

**Comment by ArthurG** [comment]
Duplicate of #112
