### ISSUE TITLE
Unable to post/re-post!

### ISSUE THREAD

**Issue by JanYalda** [ArthurG/Kijiji-Repost-Headless#163]
I've tried to re-post an existing ad and it didn't seem to work! This is after the latest update to the repo regarding the "login issue". The program uploads the image(s) successfully then it fails and re-attempts until it gives up, I checked my email and I do get a confirmation that my ad is up but nothing shows up on my list of ads. I also noticed that the email confirmation were duplicated as I tried tried to re-post once and then post once again but instead of getting only two confirmations I got four!

**Comment by Chimbobway** [comment]
I am having the same problem as well please make another update to fix it, your program is awesome man, saves me so much time. Cheers.

**Comment by jackm** [comment]
What type of ad are you trying to repost and/or post? Please provide some more background information.

I ask because I have just tried reposting an ad in one of the Buy/Sell categories and it was able to delete and post the ad without issue.

**Comment by JanYalda** [comment]
I tried a couple of ads from the same category which is "Services" and one was specifically in the "Skilled Trades"

**Comment by jackm** [comment]
I do believe that there have been issues with posting and reposting ads in the "Services" categories for quite a while now. Kijiji treats these ads differently and it likely requires some additional reverse engineering to get that to work, which we haven't figured out yet. See issue #112

**Comment by Chimbobway** [comment]
***FIX *** Okay so anyone with this issue, don't be dumb like me... Re-download and update the file LOL
