### ISSUE TITLE
After post - No listings found

### ISSUE THREAD

**Issue by linuxtechs** [ArthurG/Kijiji-Repost-Headless#164]
Hey guys. Amazing job. However, after posting, I get an email that it posted successfully. But I go to my account and there is no listings found.

Is it only me?

**Comment by linuxtechs** [comment]
# python kijiji_repost_headless post item.yaml 
Image upload success on try #1
Failed ad post attempt #2, giving up.

**Comment by jackm** [comment]
Is this an ad in the "Services" category? If so, see issue #112

**Comment by linuxtechs** [comment]
Yes it is.

Thanks!
