### ISSUE TITLE
Address issue

### ISSUE THREAD

**Issue by vowswithin** [ArthurG/Kijiji-Repost-Headless#165]
While trying to post a condo in the Ajax Ontario region I received the following error

Choose most relevant category relating to "". [To skip, enter 'skip'] [To restart, enter 0]: 1
Your address:  ** hirshfield lane ajax ontario
Found one result: **, Hirshfield Lane, Ajax, Durham Region, Golden Horseshoe, Ontario, L1Z 1E8, Canada
Address is too vague; city is missing! Try again.

Your address:

I took out the house number for this post and replaced with ** but you get the idea... and when I copy the exact address that it managed to find and past it back in it keeps saying "address is too vague" 

I assume this is some sort of back end error as it looks like it is doing what its supposed to since it even finds the address but just wont accept it.

Let me know if you need further information, thanks for your work :-)

**Comment by ArthurG** [comment]
AFAIK this should be fixed now. Please reopen if you are facing issues.
