### ISSUE TITLE
Cannot log in 2020-02-05

### ISSUE THREAD

**Issue by Rings4** [ArthurG/Kijiji-Repost-Headless#166]
Hi, there's another "cannot log in" issue as of 2020-02-05.

**Comment by jackm** [comment]
Are you using the latest commit?

**Comment by sylvainstmartin** [comment]
give me a link to it... not sure :/

its 2.0 i use

**Comment by jackm** [comment]
Just pull the latest commit from this repo.

I'm not sure what you mean by "its 2.0", this project hasn't been incrementing any version number.

**Comment by Rings4** [comment]
> Just pull the latest commit from this repo.
> 
> I'm not sure what you mean by "its 2.0", this project hasn't been incrementing any version number.

I don't even know who that is. Op here, I'm using the latest version.

**Comment by Rings4** [comment]
I'm trying it again now and it is working. Here's a screenshot of the error I got yesterday: https://i.imgur.com/dDf5eB0.png

Not sure what happened but all is fine now.
