### ISSUE TITLE
error when creating yaml file.

### ISSUE THREAD

**Issue by Subaharan1202** [ArthurG/Kijiji-Repost-Headless#168]
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "kijiji_repost_headless\__main__.py", line 200, in <module>
    main()
  File "kijiji_repost_headless\__main__.py", line 51, in main
    args.function(args)
  File "kijiji_repost_headless\__main__.py", line 196, in generate_post_file
    generator.run_program()
  File "kijiji_repost_headless\generate_post_file.py", line 199, in run_program
    address_map = restart_function(get_address_map)
  File "kijiji_repost_headless\generate_post_file.py", line 109, in restart_function
    returned_value = func()
  File "kijiji_repost_headless\generate_post_file.py", line 34, in get_address_map
    resp.raise_for_status()
  File "C:\Program Files\Python36\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://nominatim.openstreetmap.org/search?q=Brampton%2C+ON%2C+Canada&addressdetails=1&format=json

**Comment by jackm** [comment]
Possibly due to [Openstreetmap thinking that you are violating their terms of service](https://help.openstreetmap.org/questions/24740/why-am-i-all-of-a-sudden-getting-error-403) and thus blocking you specifically.

I can verify that this OSM query returns results for me when I send the request from my end. Have you been going over their rate limit of one request per second?

We may need to look at including a truthful HTTP referer or UserAgent string to identify this project when we make queries to OSM.

**Comment by Subaharan1202** [comment]
i just tried first time but didn't work and i didn't do anything to violation

**Comment by Subaharan1202** [comment]
[{"place_id":235780634,"licence":"Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright","osm_type":"relation","osm_id":2407358,"boundingbox":["43.6018018","43.8480959","-79.8888473","-79.6302939"],"lat":"43.6858146","lon":"-79.7599337","display_name":"Brampton, Peel Region, Golden Horseshoe, Ontario, Canada","class":"boundary","type":"administrative","importance":0.8268914513324357,"icon":"https://nominatim.openstreetmap.org/images/mapicons/poi_boundary_administrative.p.20.png","address":{"city":"Brampton","county":"Peel Region","state_district":"Golden Horseshoe","state":"Ontario","country":"Canada","country_code":"ca"}},{"place_id":16646012,"licence":"Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright","osm_type":"node","osm_id":1551461111,"boundingbox":["43.6818917","43.6918917","-79.7696832","-79.7596832"],"lat":"43.6868917","lon":"-79.7646832","display_name":"Brampton, Railroad Street, Ridgehill, Brampton, Peel Region, Golden Horseshoe, Ontario, L6X 1R2, Canada","class":"railway","type":"station","importance":0.6787056755444555,"icon":"https://nominatim.openstreetmap.org/images/mapicons/transport_train_station2.p.20.png","address":{"station":"Brampton","road":"Railroad Street","neighbourhood":"Ridgehill","city":"Brampton","county":"Peel Region","state_district":"Golden Horseshoe","state":"Ontario","postcode":"L6X 1R2","country":"Canada","country_code":"ca"}},{"place_id":78346303,"licence":"Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright","osm_type":"node","osm_id":7034733826,"boundingbox":["43.6864776","43.6865776","-79.7661082","-79.7660082"],"lat":"43.6865276","lon":"-79.7660582","display_name":"Brampton, Railroad Street, Ridgehill, Brampton, Peel Region, Golden Horseshoe, Ontario, L6X 1R2, Canada","class":"railway","type":"stop","importance":0.32100000000000006,"address":{"address29":"Brampton","road":"Railroad Street","neighbourhood":"Ridgehill","city":"Brampton","county":"Peel Region","state_district":"Golden Horseshoe","state":"Ontario","postcode":"L6X 1R2","country":"Canada","country_code":"ca"}},{"place_id":274545744,"licence":"Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright","osm_type":"node","osm_id":5875522755,"boundingbox":["43.6872293","43.6873293","-79.7623089","-79.7622089"],"lat":"43.6872793","lon":"-79.7622589","display_name":"Brampton, Brampton Bus Terminal, Ridgehill, Brampton, Peel Region, Golden Horseshoe, Ontario, L6X 1R2, Canada","class":"railway","type":"stop","importance":0.32100000000000006,"address":{"address29":"Brampton","road":"Brampton Bus Terminal","neighbourhood":"Ridgehill","city":"Brampton","county":"Peel Region","state_district":"Golden Horseshoe","state":"Ontario","postcode":"L6X 1R2","country":"Canada","country_code":"ca"}}]



X-Firefox-Spdy | h2
-- | --
access-control-allow-methods | OPTIONS,GET
access-control-allow-origin | *
content-type | application/json; charset=UTF-8
date | Fri, 14 Feb 2020 07:21:29 GMT
expect-ct | max-age=0, report-uri="https://openstreetmap.report-uri.com/r/d/ct/reportOnly"
server | Apache/2.4.29 (Ubuntu)
strict-transport-security | max-age=31536000; includeSubDomains; preload

its working when i put the url in the browser

**Comment by Subaharan1202** [comment]
i fixed it by adding  UserAgent parameter in the request function

**Comment by ArthurG** [comment]
Can you Submit a pull request for your fix please?
