### ISSUE TITLE
script unable to log in,

### ISSUE THREAD

**Issue by QwertyCoolMT** [ArthurG/Kijiji-Repost-Headless#170]
user/pass removed for security, but unable to log in with script.

> python3 KijijiBot -u user -p password post ad-01.yml
> Traceback (most recent call last):
>   File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "KijijiBot/__main__.py", line 204, in <module>
>     main()
>   File "KijijiBot/__main__.py", line 51, in main
>     args.function(args)
>   File "KijijiBot/__main__.py", line 87, in post_ad
>     while not check_ad(args) and attempts < 5:
>   File "KijijiBot/__main__.py", line 176, in check_ad
>     api.login(args.username, args.password)
>   File "KijijiBot/kijiji_api.py", line 102, in login
>     raise KijijiApiException("Could not log in.", resp.text)
> kijiji_api.KijijiApiException: Could not log in.
> See kijijiapi_dump_20200228T180809.html in current directory for latest dumpfile.
>

**Comment by ArthurG** [comment]
I cannot reproduce. Can you tell me what category?

**Comment by QwertyCoolMT** [comment]
Don’t think the category should matter I can’t even log in. But real estate lease 

-- 
Erich D'Atri-Guiran

**Comment by ArthurG** [comment]
Cannot repro.
