### ISSUE TITLE
[Feature Request] Generate item.yaml from existing Ad

### ISSUE THREAD

**Issue by fandy** [ArthurG/Kijiji-Repost-Headless#172]
Would be nice to not have to recreate the ad in CLI (takes a while and not user friendly), but instead use an existing ad and generate item.yaml from it.

**Comment by ArthurG** [comment]
Yes, this would be useful. Would someone like to take a stab at this one?

**Comment by jackm** [comment]
This is essentially the same request as #64 (albeit that one references the old ad post format)

**Comment by ArthurG** [comment]
Closed as issue is  duplicate
