### ISSUE TITLE
Can't create .yaml file error

### ISSUE THREAD

**Issue by seenvp** [ArthurG/Kijiji-Repost-Headless#173]
I went through all the commands with no issue, it is the last question where it asks "Your address" doesn't matter what I enter I keep getting the same error.

Attached is the screenshot of the error.

![image](https://user-images.githubusercontent.com/62871572/77882694-7e869500-722f-11ea-9a8d-181f1a76b632.png)

**Comment by getsec** [comment]
Try running from another network. You're getting a 403. Which is odd. Means you are being blocked by the remote host. Are you running from home?

**Comment by seenvp** [comment]
I am using this from home, I used the url to go an inspect and no issues from openstreetmap. The url opens just fine with no 403 error. The error is within the code itself, any insight would be greatly appreciated.

**Comment by jackm** [comment]
This may be related to how this tool sets its HTTP referer value.

See my comment in issue [168](168#issuecomment-586128110).

**Comment by ArthurG** [comment]
> This may be related to how this tool sets its HTTP referer value.
> 
> See my comment in issue [168](168#issuecomment-586128110).

We should properly set the user agent and see if that helps. Would anyone like to take a stab at it?

**Comment by getsec** [comment]
@ArthurG I'll take a stab at it mate.

**Comment by getsec** [comment]
@ArthurG Would you like me to create a PR through forking? Or make a PR by this repo via branch

**Comment by ArthurG** [comment]
Please open a PR on this repo @getsec

**Comment by getsec** [comment]
Sounds good I’m just testing locally then will push it up

**Comment by getsec** [comment]
@ArthurG  I'm getting a 403 trying to push my branch mate.

```
git push --set-upstream origin useragent-random
remote: Permission to ArthurG/Kijiji-Repost-Headless.git denied to getsec.
fatal: unable to access 'https://github.com/ArthurG/Kijiji-Repost-Headless/': The requested URL returned error: 403
```

**Comment by ArthurG** [comment]
You'll need to fork a repo, then push the changes to your fork. From your
fork, you can then submit a pull request to merge to my master.

**Comment by getsec** [comment]
Cheers https://github.com/ArthurG/Kijiji-Repost-Headless/pull/174 🍻

**Comment by seenvp** [comment]
Thank you for the fix !!!
