### ISSUE TITLE
Reposting ads mostly ends in duplication removal.

### ISSUE THREAD

**Issue by getsec** [ArthurG/Kijiji-Repost-Headless#175]
First off, huge shoutout to this project and contributors. Been doing this myself with headless chrome using selenium and It was pretty garbage until I found this one.

I host a few services on Kijiji for stuff and I've noticed that when I try to repost my ads I'll get a duplicate error in the kijijidump message div (html output). I've setup a Cron Job that does the "show" function and dumps that to a log file every 15 minutes. Then I have another script to grep the log and if it's empty, it will repost the ad, but for some reason I get the "oops this seems to be a duplicate" error. Any ideas here, should I update the naming convention?

Actual Error:
```Oops... Too late! This listing was so awesome that it's already gone. Check out other similar ads in your area```

Just wondering if anyone else has ran into this issue. Trying to use this to fully automate the reposting of my services ad

**Comment by ArthurG** [comment]
Is this related to #112
