### ISSUE TITLE
Halp? Token issue? 

### ISSUE THREAD

**Issue by scsikid** [ArthurG/Kijiji-Repost-Headless#177]
I've been using Kijiji repost for some time. Out of the blue this error occurred. I'm uncertain as to why. Other posts that mention kijiji_api.KijijiApiException: Element with name attribute 'ca.kijiji.xsrf.token' not found in html text. seem to indicate it's a special character in the password field, which I don't have any special characters in mine. Any help with this is appreicated.

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "kijiji_repost_headless/__main__.py", line 200, in <module>
    main()
  File "kijiji_repost_headless/__main__.py", line 51, in main
    args.function(args)
  File "kijiji_repost_headless/__main__.py", line 146, in repost_ad
    delete_ad(args, api)
  File "kijiji_repost_headless/__main__.py", line 127, in delete_ad
    api.login(args.username, args.password)
  File "kijiji_repost_headless/kijiji_api.py", line 106, in login
    'ca.kijiji.xsrf.token': get_token(resp.text, 'ca.kijiji.xsrf.token'),
  File "kijiji_repost_headless/kijiji_api.py", line 50, in get_token
    raise KijijiApiException("Element with name attribute '{}' not found in html text.".format(attrib_name), html)
kijiji_api.KijijiApiException: Element with name attribute 'ca.kijiji.xsrf.token' not found in html text.
See kijijiapi_dump_20200503T203326.html in current directory for latest dumpfile.
```

**Comment by ArthurG** [comment]
Are you on the latest version? Have there been any changes to the code?

**Comment by jackm** [comment]
I'm fairly certain this is because of the new captcha Kijiji has implemented for logging into their site.

See #176

**Comment by scsikid** [comment]
@jackm yep sounds about right. reading that issue, the timeline generally matches up to when the problem was first presented. shall i leave this issue open until 176 is resolved? or close this in anticipation?

**Comment by scsikid** [comment]
@ArthurG yes, pulled down the latest version. i didn't change a thing. freshly cloned the repo, generated an ad, noticed the issue as well.

**Comment by KingAchu** [comment]
Hey guys, I just stumbled into this code while looking for something to post ads on kijijji. I have been coding for just the last 2 years so my knowledge is not expansive. Any resolution about this issue?

 raise KijijiApiException("Element with name attribute '{}' not found in html text.".format(attrib_name), html)
kijiji_api.KijijiApiException: Element with name attribute 'ca.kijiji.xsrf.token' not found in html text.
