### ISSUE TITLE
Intermittent Can't Login LOGIN_RECAPTCHA_FAIL

### ISSUE THREAD

**Issue by michaelkuzmin** [ArthurG/Kijiji-Repost-Headless#183]
hey everyone and @ArthurG  I am so sorry if I am missing something but I just tested the script for the first time since the issue with login was closed and it is still not working for me. I am getting intermittent issues on all commands (post, nuke, show). Sometimes they work and sometimes they do not:
`{"errors":[{"message":"Something went wrong during authentication.","locations":[{"line":2,"column":3}],"path":["loginUser"],"extensions":{"errorCode":"LOGIN_RECAPTCHA_FAIL","statusCode":401}}],"data":{"loginUser":null}}`

what is the consensus on this? do we need to script around this to attempt many times until it randomly succeeds? seems a bit risky... 

I have to say I am a little confused why I am the first person posting this issue. surely this happened to everyone else? unless something changed again with the captcha logic recently?...

**Comment by michaelkuzmin** [comment]
Duplicate of #176

**Comment by Rings4** [comment]
I made a similar post the other day actually. I can't post any ads myself.
https://github.com/ArthurG/Kijiji-Repost-Headless/issues/182

**Comment by michaelkuzmin** [comment]
> I made a similar post last week actually. I can't post any ads myself.
> #182

no, what you are experiencing is something else. let me comment on your thread to keep things cleaner.

**Comment by ArthurG** [comment]
Looks like it is related to #198
