### ISSUE TITLE
Can't log in - INTERNAL_SERVER_ERROR

### ISSUE THREAD

**Issue by kkkkkasper** [ArthurG/Kijiji-Repost-Headless#185]
Been having this problem every time i try to post yesterday and today
Account is not banned, just posted an ad on mobile

`{"errors":[{"message":"Variable \"$input\" got invalid value \"NEW_AJAX_LOGIN\" at \"input.hints[0]\"; Expected type Hints.","locations":[{"line":1,"column":20}],"extensions":{"errorCode":"INTERNAL_SERVER_ERROR"}}]}`

**Comment by data4ryan** [comment]
I've been getting this too.  I think my last action was editing price from the mobile app.

**Comment by kheniparth** [comment]
Debugged and found that if you remove this line then it works. Because Kijiji API doesn't pass the hint parameter in the login POST request. If it works for everyone then I will create a pull request. So please let me know if this fix works for you or not.

https://github.com/ArthurG/Kijiji-Repost-Headless/blob/086665d6765cf20c367c7d007ef3754eb9733e10/kijiji_repost_headless/kijiji_api.py#L112

**Comment by ArthurG** [comment]
> Debugged and found that if you remove this line then it works. Because Kijiji API doesn't pass the hints parameter in the login POST request. If it works for everyone then I will create a pull request. So please let me know if this fix works for you or not.
> 
> https://github.com/ArthurG/Kijiji-Repost-Headless/blob/086665d6765cf20c367c7d007ef3754eb9733e10/kijiji_repost_headless/kijiji_api.py#L112

Can you please make a PR for that fix?

**Comment by EEG-Brain-Scanner** [comment]
running amazing again (after removing line 112)! Thanks for the hard work and sorry for opening pretty much a duplicate case by accident. ty ArthurG!!!

**Comment by kkkkkasper** [comment]
Worked for me :)

**Comment by prgrm** [comment]
Worked for me too.

**Comment by kheniparth** [comment]
> > Debugged and found that if you remove this line then it works. Because Kijiji API doesn't pass the hints parameter in the login POST request. If it works for everyone then I will create a pull request. So please let me know if this fix works for you or not.
> > https://github.com/ArthurG/Kijiji-Repost-Headless/blob/086665d6765cf20c367c7d007ef3754eb9733e10/kijiji_repost_headless/kijiji_api.py#L112
> 
> Can you please make a PR for that fix?

Here it is: https://github.com/ArthurG/Kijiji-Repost-Headless/pull/187

Cheers
