### ISSUE TITLE
Auto run commands?

### ISSUE THREAD

**Issue by kdr0588** [ArthurG/Kijiji-Repost-Headless#191]
Question for the community. The repost headless is awesome! How would you auto run the commands when the computer starts?

**Comment by Jester8813** [comment]
I created batch files to repost ads. While using the schedule tasks in windows to set specific times to run these ads.

**Comment by kdr0588** [comment]
Ah yes, windows task scheduler is a good idea! 

How did you do the batch files?

**Comment by torqueNoFriction** [comment]
This is the batch file I create. This script works if set in the parent folder, such that all the configuration files are also in this folder. For  example my file/folder layout is:

Main Folder
   |->shoes.yml
   |-> (... other kijjji add configurations ending with .yml)
   |-> post_all_adds.bat (this is my batch file containing the script below)
   |-> kijijiPoster
          |-> This folder contains the repo itself

   
The following is my batch script:

```
REM Script by TorqueNoFriction
REM Last Updated: 08/09/2018
REM Based of https://github.com/ArthurG/Kijiji-Repost-Headless

@echo off
set mypath=%~dp0

echo Executing %mypath%kijijiPoster git pull ...

echo Executing %mypath%kijijiPoster\kijiji_repost_headless repost ...

for /R %mypath% %%f in (*.yml) do (
echo %%f
python %mypath%kijijiPoster\kijiji_repost_headless repost %%f
)
```

**Comment by kdr0588** [comment]
The batch script didn't work for me 😞  I think it might be because I didn't set the path correctly. 

My folder structure is a bit different:
```
Kijiji-Repost-Headless
       |-> Rental1
                 |-> rental1.yaml
                 |-> photo1.jpg
                 |-> photo2.jpg
       |-> Rental2
                 |-> rental2.yaml
                 |-> photo1.jpg
                 |-> photo2.jpg
       |-> kijiji_repost_headless
                 |-> __main__.py 
                 |-> _all the other python scripts from repo_
       |-> repost_all_ads.bat

```

I don't have the .yml configurations (_I don't know why but mine is .yaml_) in the parent folder because I have a bunch of photos for each ad. So having its separate folder seems more organized. 

How do I adjust the batch code to reflect the correct path?

**Comment by Jester8813** [comment]
Hi Sorry it took me a while to reply here is the bat i use.

cd C:\Python35

python kijiji_repost_headless -u emailAddress@gmail.com -p password repost KijijiADs\CompanyAD1\CompanyAD1.yaml

**Comment by kdr0588** [comment]
**Thank you Torque and Jester!!** I got the batch file is working! Jester's was simple enough for me to edit with my beginner level coding skills LOL.

**Follow up question:** I recently noticed that my listings on Facebook Marketplace seem to get more hits than Kijiji. What do you guys use to auto-list on Facebook?
