### ISSUE TITLE
Perhaps I am retarded. But, I can't seem to get this working.

### ISSUE THREAD

**Issue by Zackorus** [ArthurG/Kijiji-Repost-Headless#199]
If someone can help me get this working, I could compensate them $20.

**Comment by jackm** [comment]
I believe that login capability is broken right now. See #198

**Comment by Zackorus** [comment]
Sorry I should have been more specific. I have never used python. I downloaded, python, and am trying to figure out what I need to do to get this Kijiji bot working. I know how to edit files and in one file I managed to input my username in place of the empty quotes. And I installed the prerequisite files. But, I just don’t know what to do from there. Do the github files need to be in some special directory?

**Comment by Aluui** [comment]
Hi @Zackorus, I can help you set this up. I know how frustrating it was for me.
Add me on skype coolchibs@gmail.com

**Comment by ArthurG** [comment]
Please provide more context into your problem. It may be fixed by #198
