### ISSUE TITLE
Missing attributes for Real Estate

### ISSUE THREAD

**Issue by erikdvlp** [ArthurG/Kijiji-Repost-Headless#205]
When creating a new ad for the Real Estate section, many options are unaccounted for, including:

- Appliances
- Personal outdoor space
- Building amenities
- Utilities included
- All virtual options

And likely others. Additionally, many of the ones that are accounted for haven't been assigned human-readable attribute names, resulting in blanks when generating an ad:

`Choose most relevant category relating to "". [To skip, enter 'skip'] [To restart, enter 0]:`

Both issues are easily fixed by adding the missing items to `kijiji_categories_attrs.json`.

**Comment by abdulzeedo** [comment]
Honestly, real estate should just use their own platform and stop putting junk on Kijiji...
