### ISSUE TITLE
Ask for phone number when generating inf file

### ISSUE THREAD

**Issue by orditeck** [ArthurG/Kijiji-Repost-Headless#36]
I add `postAdForm.phoneNumber=` myself in the `item.inf` but maybe you could ask that info when generating the inf file?

**Comment by guoarthur** [comment]
I want to minimize the effort required to use this script, hence, I want to minimize the number of required input fields (or fields where you can include an empty line).

I'm thinking of setting a flag inside the GenerateInfFile.py to allow users to turn on optional fields if they want. Opinions?

**Comment by JackDell** [comment]
Just allow people to input like 's' to skip or something. Having 1 extra field is really not a big deal, and I think that having a phone number with the add is a pretty common thing.

**Comment by ArthurG** [comment]
This should be solved now!
