### ISSUE TITLE
XSFR token fix is broken

### ISSUE THREAD

**Issue by jimmyp22** [ArthurG/Kijiji-Repost-Headless#61]
Tried posting an ad with the latest kijiji_api.py and got a token error. Reverted back to kijiji_api.py before the token fix and it works fine.

**Comment by jackm** [comment]
@jimmyp22 is this still broken for you? I cannot reproduce this using an up to date repo.

**Comment by resiproxy** [comment]
Was working fine for me, posted a few ads and now getting this issue. Not sure what the dumps mean
