### ISSUE TITLE
Reposting From Folder Broken After Nov 1, 2017 Build

### ISSUE THREAD

**Issue by EmRav** [ArthurG/Kijiji-Repost-Headless#62]
As of Nov 1, 2017's build (after this build, it works with this version), reposting from folders does not work.

Example command with current build:
python kijiji_repost_headless repost_folder KIJIJI-ADS/1-CVAIO

Output:
usage: kijiji_repost_headless [-h] [-u USERNAME] [-p PASSWORD]
                              {post,folder,repost_folder,show,delete,nuke,check_ad,repost,build_ad}
                              ...

Post ads on Kijiji

positional arguments:
  {post,folder,repost_folder,show,delete,nuke,check_ad,repost,build_ad}
                        sub-command help
    post                post a new ad
    folder              post ad from folder
    repost_folder       post ad from folder
    show                show currently listed ads
    delete              delete a listed ad
    nuke                delete all ads
    check_ad            check if ad is active
    repost              repost an existing ad
    build_ad            Generates the item.inf file for a new ad

optional arguments:
  -h, --help            show this help message and exit
  -u USERNAME, --username USERNAME
                        username of your kijiji account
  -p PASSWORD, --password PASSWORD
                        password of your kijiji account

Example Output With Nov 1 Build (same command):
Existing ad deleted before reposting
Image Upload success on try #1
Image Upload success on try #1
Image Upload success on try #1
Image Upload success on try #1
Image Upload success on try #1
Image Upload success on try #1
Image Upload success on try #1

**Comment by cerberii** [comment]
do not fix

**Comment by EmRav** [comment]
Cerberii, why on earth not? The repost folder feature is broken.

**Comment by jackm** [comment]
Could you provide more info on your working environment such as folder structure, OS, etc?

**Comment by EmRav** [comment]
OS: Windows 10 Pro 64-bit

FOLDER STRUCTURE
K:.
|   filelist.txt
|   requirements.txt
+---KIJIJI-ADS
|   +---1-CVAIO
|   +---2-C780
|   +---3-C441
+---kijiji_repost_headless
|   \---__pycache__


Each folder in KIJIJI-ADS Contains the following structure:
1.jpg
2.jpg
3.jpg
4.jpg
5.jpg
6.jpg
7.jpg
item.inf
login.inf

I execute these commands on each folder in a cmd

K:
cd K:\
RMDIR /S /Q K:\kijiji_repost_headless\__pycache__
python kijiji_repost_headless repost_folder KIJIJI-ADS/1-CVAIO


This all works except in builds after Nov 1, 2017's commits. I can't seem to repost from folders afterwards. Does this help?

**Comment by cerberii** [comment]
this is not a kijiji repost problem.

have you looked at what directory your python is located?  have you tried absolute directories?  have you tried installing linux and deleting windows?  format c: , thx.

**Comment by EmRav** [comment]
Cerberii, seriously, lay off with being condescending. Python is in C:/Python if you are actually interested. I am providing useful feedback and you are doing nothing of use here my good man. 

The issue only occurs after the changes I mentioned above. This means that something has been changed in this project to cause the issue,  since I have changed nothing but updating the project.

Have you tried uninstalling your tendency to be an unhelpful dick, format and reinstall your brain?:, thx.

**Comment by jackm** [comment]
I can't seem to reproduce this. I too am using Windows 10 Pro 64bit with git-scm. I made a temp folder with the repo files in it and I also made a "KIJIJI-ADS" listings folder in the project root folder with an ad folder under that.

I was able to post the ad and also run a "repost_folder" command to repost the ad without issue. For some reason you seem to just be getting the help menu output when you run the kijiji_repost_headless module.

Are you able to reproduce this problem by checking out the token fix commit (hash e64a478...)? And does the problem disappear again if you checkout the repo one commit before (hash 228d43b...) the token fix commit?

**Comment by cerberii** [comment]
I was only thinking your directory relational structure could be the problem.  have you tried specifying absolute paths?  have you tried placing the project in c:?  the problem could be that you need to specify the path.  python3 kijij-repost-headless repost_folder K:\ads\ad1
