### ISSUE TITLE
 Element with name attribute 'userId' not found in html text.

### ISSUE THREAD

**Issue by vipertemp** [ArthurG/Kijiji-Repost-Headless#65]
Having this error since around 1400h this afternoon. 
Prior to this everything had been working well for months without any issues.

"Element with name attribute 'userId' not found in html text"

Thrown from: 
raise KijijiApiException("Element with name attribute '{}' not found in html text.".format(attrib_name), html)
in
def get_token(html, attrib_name)

**Comment by Tontiwisk** [comment]
@vipertemp 

Here's my fix: 

Change this     

```
if not res:
        raise KijijiApiException("Element with name attribute '{}' not found in html text.".format(attrib_name), html)
return res[0]['value']
```

to this 


```
    if not res:
        print("Token '{}' not found in html text.".format(token_name))
        return ""
    return res[0]['value']
```

Turns out you don't need that token anyway. The link that uses it still gets a proper JSON response without it.

**Comment by vipertemp** [comment]
Your fix worked like perfectly, thank you!
