### ISSUE TITLE
Post problem

### ISSUE THREAD

**Issue by wyru5** [ArthurG/Kijiji-Repost-Headless#68]
hello,

with command:
 python kijiji_repost_headless repost_folder 1 
I was able to repost but today I am getting this info after entering the command:
usage: kijiji_repost_headless [-h] [-u USERNAME] [-p PASSWORD]
                              {post,folder,repost_folder,show,delete,nuke,check_ad,repost,build_ad}
                              ...

Post ads on Kijiji

positional arguments:
  {post,folder,repost_folder,show,delete,nuke,check_ad,repost,build_ad}
                        sub-command help
    post                post a new ad
    folder              post ad from folder
    repost_folder       post ad from folder
    show                show currently listed ads
    delete              delete a listed ad
    nuke                delete all ads
    check_ad            check if ad is active
    repost              repost an existing ad
    build_ad            Generates the item.inf file for a new ad

optional arguments:
  -h, --help            show this help message and exit
  -u USERNAME, --username USERNAME
                        username of your kijiji account
  -p PASSWORD, --password PASSWORD
                        password of your kijiji account

Any ideas please?

**Comment by vipertemp** [comment]
I have a similar problem, I am unable to view my current ads. Something in the JSON may have changed?

**Comment by jackm** [comment]
I just tried debugging this, and it would appear that an exception is thrown within the `get_all_ads` function (which is called to determine the ad ID that needs to be deleted first before reposting the same ad).

What is causing this is that the HTTP request to `https://www.kijiji.ca/j-get-my-ads.json` returns a 404 status code. `get_all_ads` then tries to search through the HTTP body text but of course there are no ad IDs there.

Kijiji has once again changed their site. We will have to either find the new URL that Kijiji is using for their json requests or use a different method to get the list of active ads along with their ad IDs.

**Comment by wyru5** [comment]
thanks guys, I cant do much from programming side so I hope so somebody will be able to find way around and keep us posted.

**Comment by Peppershaker** [comment]
same here, json decode problem

**Comment by jackm** [comment]
Fixed. It didn't actually take that long to find a new url to get active ad info from.

You can clone my [`get-ads-fix`](https://github.com/jackm/Kijiji-Repost-Headless/tree/get-ads-fix) branch from my repo in the mean time until my pull request (GH-69) is accepted.

**Comment by wyru5** [comment]
Works, thanks man, nice job!

**Comment by Peppershaker** [comment]
thanks a ton

**Comment by orditeck** [comment]
@ArthurG could you please accept the PR https://github.com/ArthurG/Kijiji-Repost-Headless/pull/69?

**Comment by ArthurG** [comment]
@orditeck  done

**Comment by jackm** [comment]
@ArthurG this issue can be closed now
