### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'C:\\ad\\pic'

### ISSUE THREAD

**Issue by resiproxy** [ArthurG/Kijiji-Repost-Headless#79]
Having a permission issue. Using windows 10, using administrative cmd prompt.

Any idea?

**Comment by jackm** [comment]
Check the permissions on both the file and the containing folder.

The error is pretty self-explanatory; you don't have permissions to read/write (you didn't say which) to that file or folder.

I would suggest not using a folder in the root of your C drive. Use a folder within your user directory if you want to avoid permissions problems.

**Comment by resiproxy** [comment]
Oh sorry forgot to say i already validated the permissions, gave full control to all users.

Originally the file/folder was in my user directory, moved it to C:\ to see if that would have made a difference. Tried both administrative CMD prompt and powershell

**Comment by jackm** [comment]
You need to provide more information on what leads to this error you're seeing. What are the arguments you're using when calling kijiji_repost_headless? Could you post the full stack trace?

**Comment by resiproxy** [comment]
Created my yml file using "python kijiji_repost_headless build_ad" and followed the prompts.

Place image in a folder relative to the yml file in a folder called "picture". Parent folder is called "Mississauga" and within that folder is the item.yml file and then a folder named "picture"

I then run "python kijiji_repost_headless post Mississauga\item.yml" and get the following error:

Note: A recent update has broken all previously generated .inf files. Please regenerate all your files - this script is not backwards compatible with previous versions. The commands are also changed. See README for details.
Traceback (most recent call last):
  File "C:\Users\Desktop\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Desktop\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "kijiji_repost_headless\__main__.py", line 191, in <module>
    main()
  File "kijiji_repost_headless\__main__.py", line 50, in main
    args.function(args)
  File "kijiji_repost_headless\__main__.py", line 80, in post_ad
    [data, image_files] = get_post_details(args.ad_file)
  File "kijiji_repost_headless\__main__.py", line 68, in get_post_details
    files = [open(os.path.join(os.path.dirname(ad_file), picture), 'rb').read() for picture in data['image_paths']]
  File "kijiji_repost_headless\__main__.py", line 68, in <listcomp>
    files = [open(os.path.join(os.path.dirname(ad_file), picture), 'rb').read() for picture in data['image_paths']]
PermissionError: [Errno 13] Permission denied: 'Mississauga\\picture'

Note quite sure what i am doing wrong.

**Comment by resiproxy** [comment]
I am an idiot, was not specifying the file name just the folder. sigh.
