### ISSUE TITLE
Enhancement:  Emulate person better

### ISSUE THREAD

**Issue by sgbotsford** [ArthurG/Kijiji-Repost-Headless#83]
While kijiji has a 10 second between posts  requirement, as automaters get better, they will get wise to this.  I suggest a user setable time between posts, and a random window.  E.g. 5 minutes, +- 1 minute.

**Comment by ArthurG** [comment]
There is currently a ~2 minute delay from the time someone deletes an ad and the time the ad is reposted. This is good enough until Kijiji catches on, then we can think about increasing complexity.
