### ISSUE TITLE
Enhancement:  Delete and Repost.

### ISSUE THREAD

**Issue by sgbotsford** [ArthurG/Kijiji-Repost-Headless#84]
Scrape the existing ad and build the item file.  This allows people to use the kijiji composer if they wish.  This also allows reposting before the time has expired.

Kijiji currently has a limit of 8 ads in a given category.  If you can delete ads automatically, you can rotate ads.  E.g. You post one a day.  Once you get to 8 ads you delete the oldest one and post a new one.

**Comment by jackm** [comment]
Generating an ad file by scraping an existing ad from Kijiji was already suggested in issue #64. You don't really need to scrape the contents of an existing ad directly from Kijiji if you have the ad file that you used to post it. I'm not sure what you're trying to solve here.

I'm also not sure what you mean by "reposting before the time has expired". You can always repost an ad early using the `repost` subcommand. This is _the_ main use of the Kijiji-Repost-Headless project.

As for "rotating" ads, I would argue that you should not have 8 identical ads all in the same category posted 24 hours apart. This just clutters up the Kijiji ad space in general. It would be better to always delete the single existing old ad and then repost it - which is the way it works right now.

**Comment by sgbotsford** [comment]
Sorry.  I thought I'd scanned the old issues.  Should I delete here, and comment there?  I'm familiar only with the usual kijiji practice that no repost is possible until the ad is about to expire.  

Scraping the existing ad allows you to not have to rebuild all your ads from scratch.  As well, working in the Kijiji interface may be less error prone.  This also makes it easy to move an ad from city to city.

As to 8 ad limit.  I currently sell 80 kinds of trees.  I group them in various ways, but currently have 30 some ads running in two provinces.  To use the free ad option I need to maintain about 120 ads total.

**Comment by jackm** [comment]
I understand what you're talking about, however most of the features you're looking for aren't there yet. This program is not really an ad manager, but rather provides a more automated way to post, delete and repost ads.

Doing things like reposting an existing ad to a different city or province would have to be done manually or with some other external program that could edit the ad posting files beforehand. The majority of people usually don't have more than 10 to 15 ads active at a time; certainly not 100+ ads that they're managing.

If you want greater control of managing hundreds of ads, then you might want to look for a paid solution like [Kijiji Admarkt](https://kijijiforbusiness.ca/en/admarkt/) or maybe a third party solution (if you can trust them).

**Comment by sgbotsford** [comment]
This, I think will work just fine, with just a bit of scripting.  In passing I use admarkt, but it doesn't work as well as the free ads.

The following might be included in the Wiki.

In passing:  As someone who has maintained ads continuously for several years.

* Don't be greedy.  Aim for 1 ad per page.  Make reference in the ad, "To see all by stuff click on "show posters other ads" at right. If everyone used this this unreasonably, Kijiji becomes useless for everyone, and kijiji will stop doing free ads.



* Most people will scan 3 pages if they are looking for something they can't search for.  So you need one ad in the first couple of pages to get attention.

* Many people will look for something for several days.  If you rotate your ads on a schedule that isn't a multiple of 24, you have a better chance of catching them when they are looking.  E.g. On monday you post at 8 a.m. on Tuesday you post at 1 p.m.  On Wednesday you post at 6 p.m.  On Thursday you post at 11 p.m.  Someone surfing on their 10:30 coffee break will catch the Monday posting while the evening reader will catch the Wednesday one.

* Kijiji doesn't index your whole ad for its searches, but only indexes somewhere between 200 and 500 characters. (Not sure how much) Make sure you have your keywords there.

* Use your headline space. It varies from time to time, but try to use it all.

* Kijiji displays a snip of text from your ad with the headline.  Use it effectively.  

* A set price gets more interest than "Please contact"  

* If you are selling multiple items in an ad, set a typical price.  I use a price that  would include half the items below it.  So if you have 20 small picture frames at 3 bucks, and 8 large frames at 10 bucks, put down a price closer to 3 than to 10.  If you can, list what you have in the headline.  "Small + large picture frames starting at $3"

* Group things that will appeal to the same person.  Baby clothes and tools aren't a good combo. 

* If you are selling multiple items,  list the price for each in your ad.

* People don't read, they skim.  Don't write an ad longer than a single screen.

**Comment by alumbs** [comment]
Quick note on this issue: If the ad deletion mechanism relies on the title to delete the ad, then you can just have 8 different titles, schedule 8 scripts to run every 8 days (one script a day), and each script just runs the 'python ... repost ...' command. If this sounds like it can help you, comment below or reach out to me and i'll help you set it up.

**Comment by ArthurG** [comment]
I don't intend to support this feature. It adds complexity to the program that could be handled by something like clever bash scripts and/or cron jobs.
