### ISSUE TITLE
Enhancement:  Multiple user support.

### ISSUE THREAD

**Issue by sgbotsford** [ArthurG/Kijiji-Repost-Headless#85]
Because of the 8 free ad in any one category, being able to support multiple users.  E.g. I use ID 1 for  8 ads, and ID 2 for 8 ads.

**Comment by jackm** [comment]
This is already possible. Just change the login credential fields ("username" and "password") in the ad file to whatever Kijiji account you want it to use to post the ad. You can use a different account to post each ad if you want to.

If you use the username and password _arguments_ (ie. `-u` and `-p`) when calling kijiji_repost_headless, then this will override any username and password that is set in the ad file itself.

**Comment by sgbotsford** [comment]
Thank you.  I think it's time for me to shutup and play with it some more.
