### ISSUE TITLE
Crash on build_ad

### ISSUE THREAD

**Issue by sgbotsford** [ArthurG/Kijiji-Repost-Headless#88]
* Got the category.

* Didn't give option between Owner and business, but presented each one as a separate question.

* After entering address, it crashed.  

I initially tried the address I use on ads

50042 Range Road 31, Warburg, AB, T0C 2T0

Second pass I just did
RR 1, site 2 box 5

Transcript of session.

python kijiji_repost_headless build_ad
Note: A recent update has broken all previously generated .inf files. Please regenerate all your files - this script is not backwards compatible with previous versions. The commands are also changed. See README for details.
****************************************************************
* Creating the item.yml file. Please answer all the questions. *
****************************************************************

Your ad must be submitted in a specific category.
Please provide a category keyword to search for: plants
 1 - Home Outdoor > Plants, Fertilizer & Soil
Select a category from the list above (choose number) [To restart, enter 0]: 1
1                                         Owner
Choose most relevant category relating to For Sale By: [To restart, enter 0] : 1
1                                         Business
Choose most relevant category relating to  [To restart, enter 0] : 
Enter a valid number!
Choose most relevant category relating to  [To restart, enter 0] : 1
Your address: 50043 Range Road 31, Warburg, AB T0C2T0
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "kijiji_repost_headless/__main__.py", line 191, in <module>
    main()
  File "kijiji_repost_headless/__main__.py", line 50, in main
    args.function(args)
  File "kijiji_repost_headless/__main__.py", line 187, in generate_post_file
    generator.run_program()
  File "kijiji_repost_headless/generate_post_file.py", line 140, in run_program
    addressMap = get_address_map()
  File "kijiji_repost_headless/generate_post_file.py", line 25, in get_address_map
    latlng = json.loads(resp.text)['results'][0]['geometry']['location']
IndexError: list index out of range

**Comment by sgbotsford** [comment]
Further info:
More experimenting shows that not all addresses fail.  I typed in my company name, and it didn't crash, but then asked me province, then city, then region of city.

I was able to create the item.yaml file without a hitch from that point.

I then tried just typing in the name of the city.  Edmonton.  Not happy with that.

Tried warburg water slides.  That passes muster.

**Comment by jackm** [comment]
It is all dependent on what Google maps API will return for an address. Some queries do not return any full address (postal code, city or province are missing) while other seemingly vague queries do return full addresses.
