### ISSUE TITLE
Category Keyword Issue

### ISSUE THREAD

**Issue by tugga82** [ArthurG/Kijiji-Repost-Headless#92]
Hi,
When I run the python3 kijiji_repost_headless build_ad, it asks me to Please provide a category keyword to search for:  I get the following error for whatever related categories I type

Could not find any categories using the given keyword. Try again.

Has anyone experienced this. Could you please help?

**Comment by tugga82** [comment]
Thanks for your reply. I very much tried the category names that Kijiji has, for example, I tried cars, motorcycles, clothing, etc but I ended up getting the same message like I posted. Let me know.
Thanks,

**Comment by jackm** [comment]
Keywords such as that should definitely returns results. You should also get a full list of all categories if you just press enter without typing any keywords. Are you certain that you are using the latest version of the code source? What OS are you using and how are you invoking python to start the kijiji_repost_headless program?

**Comment by tugga82** [comment]
![image](https://user-images.githubusercontent.com/38926820/39556069-a3f15fdc-4e4b-11e8-9560-adcde28d0edb.png)
I have the print screen here of what am getting. I use mac OS High Sierra version 10.13.4
Python version 3.

**Comment by jackm** [comment]
Are you using git? Can you run `git status` within the python project directory to see if all files are up-to-date? Does the file `kijiji_categories_attrs.json` contain a bunch of JSON text?

**Comment by tugga82** [comment]
Just checked the git version
git version 2.15.1 (Apple Git-101)

Will look into the other ones now

**Comment by tugga82** [comment]
When I ran git status, below is what I got Jack.

Tuggas-MBP:kijiji2018 Vidya$ git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	../.CFUserTextEncoding
	../.DS_Store
	../.Rapp.history
	../.Rhistory
	../.Trash/
	../.TurboMeeting/
	../.atom/
	../.bash_history
	../.bash_profile
	../.bash_sessions/
	../.config/
	../.dropbox/
	../.dvdcss/
	../.hwid
	../.kodi/
	../.mysql_history
	../.npm/
	../.oracle_jre_usage/
	../.profile.swp
	../.putty/
	../.rstudio-desktop/
	../.ssh/
	../.subversion/
	../.swfinfo
	../.viminfo
	../Applications/
	../Desktop/
	../Documents/
	../Downloads/
	../Dropbox/
	../Jts/
	../Library/
	../Movies/
	../Music/
	../Pictures/
	../Public/
	../VirtualBox VMs/
	../kijiji/
	../kijiji2017/
	./
	../mfeeddata.tugga82/
	../mfeeddata/
	../msi

nothing added to commit but untracked files present (use "git add" to track)

**Comment by jackm** [comment]
Run the git command within the `kijiji2018` directory - the same place you'd run python from to invoke the kijiji_repost_headless program. There should definitely be existing commits.

**Comment by tugga82** [comment]
Here is what I got Jack. I recloned everything.

Tuggas-MBP:Kijiji-Repost-Headless Vidya$ git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.DS_Store
	kijiji_repost_headless/Helmet.JPG
	kijiji_repost_headless/MotorcycleJacket.JPG

nothing added to commit but untracked files present (use "git add" to track)

**Comment by jackm** [comment]
Yes it appears that everything is up to date and present. There's no python exceptions being thrown either. I'm at a loss as to why it doesn't seem to find any categories.

**Comment by tugga82** [comment]
Those 2 images will be added only when that build command ad works is it? MAC has its own python installation version 2.6 and then I installed version 3. I am assuming the code is invoking the version 3. Earlier it also threw the YAML error and once I added the package the import error was also solved. The category is where I've been sitting at for a while now.

**Comment by jackm** [comment]
Yes it uses python 3.
You could instead just create an ad file manually, which is what the build_ad command is meant to do for you.

Here's a template. You'll want to edit the city, province, postal code, latitude, longitude, title, desc, category, price, image paths, username, password. Save it as "my_ad_file.yml" (arbitrary file name).
```
postAdForm.adType: OFFER
postAdForm.attributeMap[forsaleby_s]: ownr
postAdForm.priceType: FIXED
postAdForm.city: Your city
postAdForm.province: ON
postAdForm.postalCode: A1B 2C3
postAdForm.addressCity: Your city
postAdForm.addressProvince: ON
postAdForm.addressPostalCode: A1B 2C3
postAdForm.geocodeLat: '00.0000000'
postAdForm.geocodeLng: '00.0000000'
postAdForm.locationId: 0000000
PostalLat: '00.0000000'
PostalLng: '00.0000000'
locationLevel0: 0000000
topAdDuration: '7'
submitType: saveAndCheckout
postAdForm.title: This is the ad title
postAdForm.description: |-
  This is the ad description
  Line 2
  
  Line 4
  
  
  Line 7
categoryId: '15'
postAdForm.priceAmount: '100'
image_paths:
  - image_file_name1.jpg
  - image_file_name2.jpg
username: 'kijiji_user@example.com'
password: 'kijiji password'
```

Then you can post it using `python3 kijiji_repost_headless post path/to/my_ad_file.yml`

**Comment by jackm** [comment]
It is just a plain text file, so notepad should work fine for creating that. Save the file in the same directory as where the ad images are. It doesn't actually matter which directory, since you'll be providing the path to to the yml file when you use the _post_ command.

**Comment by ArthurG** [comment]
I've reverted my past commit which has broke the building ad command. Building ads should now work.

**Comment by tugga82** [comment]
I am going to try Jack's suggestion now. @ArthurG what does that mean? I still tried building ad command and I get the same issue.

**Comment by jackm** [comment]
He means just do a `git pull` to get the latest commit.

**Comment by tugga82** [comment]
Here is my result of git pull:

Tuggas-MBP:Kijiji-Repost-Headless Vidya$ git pull
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 2), reused 1 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), done.
From https://github.com/ArthurG/Kijiji-Repost-Headless
   0d8272c..a0099ee  master     -> origin/master
Updating 0d8272c..a0099ee
Fast-forward
 kijiji_repost_headless/kijiji_categories_attrs.json | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
Tuggas-MBP:Kijiji-Repost-Headless Vidya$

**Comment by jackm** [comment]
You're good now, you can build ads the usual way.

**Comment by tugga82** [comment]
I get this error when I key in the address:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "kijiji_repost_headless/__main__.py", line 191, in <module>
    main()
  File "kijiji_repost_headless/__main__.py", line 50, in main
    args.function(args)
  File "kijiji_repost_headless/__main__.py", line 187, in generate_post_file
    generator.run_program()
  File "kijiji_repost_headless/generate_post_file.py", line 211, in run_program
    location_id, location_area = get_location_and_area_ids()  # Returns a tuple containing location ID and area ID
NameError: name 'get_location_and_area_ids' is not defined

**Comment by ArthurG** [comment]
Should be fixed now!
