### ISSUE TITLE
Keep track of view numbers

### ISSUE THREAD

**Issue by MaximumPotato** [ArthurG/Kijiji-Repost-Headless#94]
It would be interesting to keep a log of the view count when reposting an ad.

**Comment by jackm** [comment]
Could be interesting to see, however I don't feel like it would warrant a feature in the main code base.

You're certainly free to implement your own logging system however you'd like, but I'm weary of adding too much bloat to the project.

**Comment by MaximumPotato** [comment]
Fair enough, I might just do so when I've got the time.
